export default {
    GET_USERS_LIST: 'GET_USERS_LIST',
    GET_USER_BY_ID: 'GET_USER_BY_ID',
    ADD_USER: 'ADD_USER',
    SAVE_USER: 'SAVE_USER',
    DELETE_USER: 'DELETE_USER',
    GET_GAMES_LIST: 'GET_GAMES_LIST'
};
