export default {
  SET_LOADER: 'SET_LOADER',
  SET_USERS_LIST: 'SET_USERS_LIST',
  SET_SELECTED_USER: 'SET_SELECTED_USER',
  ADD_USER:'ADD_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  SET_GAMES_LIST: 'SET_GAMES_LIST',
  SET_USER_GAMES: 'SET_USER_GAMES',
};
